### ISSUE TITLE
Where's the original firmware for M5Stack Core2?

### ISSUE THREAD

**Issue by tommy4111** [m5stack/M5Core2#114]
### Describe the bug

Can't find the original firmware with all the meters at.  I want to make some custom changes to the GUI.

### To reproduce

firmware

### Expected behavior

firmware

### Environment

- OS:
- IDE &IDE Version:
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Core2/issues?q=)
- [X] My report contains all necessary details

**Comment by Tinyu-Zhao** [comment]
Do you mean this firmware?
![IMG_9860](https://user-images.githubusercontent.com/44396641/204096212-59330edb-9774-48e4-8e06-ba47f09bbc2d.jpeg)

**Comment by tommy4111** [comment]
This one.  The one that shipped with the device.

![ide08](https://user-images.githubusercontent.com/3383551/205436833-64fd3acd-fdc5-4e0b-9e5c-62fd381b5323.png)

**Comment by Tinyu-Zhao** [comment]
The factory test program is now compatible with Core2.
https://github.com/m5stack/M5Core2/tree/master/examples/FactoryTest
