### ISSUE TITLE
AXP192 and esp32 overheating and maulfunctioning

### ISSUE THREAD

**Issue by advaithushus** [m5stack/M5Core2#116]
### Describe the bug

1.no heatsink in any ic and overheating beacause of that it is powering off sometimes mostly when a wav file is played and at charging.
2.battery bottom battery discharges so fast even when power off

current uiflow ver-1.10.9
device which i am using-M5stack core2

### To reproduce

put heatsink on ic chips and put a small fan.

### Expected behavior

to prvent overheating

### Environment

- OS:
- IDE &IDE Version:
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Core2/issues?q=)
- [X] My report contains all necessary details

**Comment by Tinyu-Zhao** [comment]
@imliubo Please help check it.
