### ISSUE TITLE
rtc_wake_up example: shutdown(RTCtime) not working as intended

### ISSUE THREAD

**Issue by pietrobalatti** [m5stack/M5Core2#132]
### Describe the bug

The example [rtc_wake_up.ino](https://github.com/m5stack/M5Core2/blob/master/examples/Basics/rtc/rtc_wakeup/rtc_wakeup.ino) does not work as intended. When pressing button C, the system does not wake up at the specified time but much before.

### To reproduce

1. Upload the  [rtc_wake_up.ino](https://github.com/m5stack/M5Core2/blob/master/examples/Basics/rtc/rtc_wakeup/rtc_wakeup.ino) program to M5Stack
2. Press Button C

### Expected behavior

Wait for system restart, it won't meet the specified time.

### Environment

- OS: Ubuntu 20.04
- IDE &IDE Version: Arduino 1.8.19
- Repository Version: 0.1.5 (updated to commit 3061135924f52ce2a6438bc8a2210216a7b44b22)

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Core2/issues?q=)
- [X] My report contains all necessary details

**Comment by Tinyu-Zhao** [comment]
You can try pulling the latest M5Core2 repository.
https://github.com/m5stack/M5Core2/commit/fb820a59fd899adebf10cbba23d0af299a16f720
