### ISSUE TITLE
Arduino IDE not finding MODULE_GRBL13.2

### ISSUE THREAD

**Issue by capedra** [m5stack/M5Core2#134]
Whenever I try to install this library on Arduino IDE, I get the following error:

![Captura de tela 2023-09-06 031811](https://github.com/m5stack/M5Core2/assets/412434/5f824aff-ae3b-4184-b1cf-f1320cd9cb36)

I guess it should look for ```MODULE_GRBL_13.2``` instead of ```MODULE_GRBL13.2```

**Comment by kartben** [comment]
I am having the same issue.

**Comment by capedra** [comment]
@Tinyu-Zhao 
@tobozo 
somebody could easily fix it in my humble opinion.

**Comment by tobozo** [comment]
@capedra until [the PR](https://github.com/m5stack/M5Core2/pull/135) is merged and a new release is produced, you can choose to install the M5Core2 library without dependencies to skip that error message.

The dependencies for M5Core2 (M5Family,M5Module-4Relay,Module_GRBL_13.2,Ethernet2) can still be installed separately.

**Comment by tobozo** [comment]
solved in latest release
