### ISSUE TITLE
Is this library deprecated? Should we switch to M5Unified?

### ISSUE THREAD

**Issue by wsanders** [m5stack/M5Core2#152]
### Describe the bug

The main class M5Core2 in the file M5Core2.h Arduino IDE library version 0.1.9, contains the following attribute:

```
class M5Core2 {
   public:
    M5Core2();
    [[deprecated(
        "It is recommended to use M5Unified Lib, which will be discontinued "
        "soon.")]] void
```
That comment makes no sense in English translation. Of course one would not want to recommend a library that will be discontinued.

Should we all be using M5Unified now?

Maybe if M5Core2 is deprecated it should be removed from the Arduino IDE library database?

### To reproduce

All environments

### Expected behavior

If library is deprecated, retranslate attribute to:

"It is recommended to use the M5Unified Lib. The M5Core2 lib will be discontinued soon."

### Environment

- OS:
- IDE &IDE Version:
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Core2/issues?q=)
- [X] My report contains all necessary details

**Comment by Tinyu-Zhao** [comment]
We will gradually migrate to Unified.

**Comment by egnor** [comment]
@Tinyu-Zhao please change the comment? It currently reads

> It is recommended to use M5Unified Lib, which will be discontinued soon.

This means that M5Unified will be discontinued soon. You should change it to this?

> It is recommended to switch to the M5Unified library. The M5Core2 library will be discontinued soon.

...which I think is what you mean?

**Comment by Tinyu-Zhao** [comment]
M5Unified will be integrated in the M5Core2 repository, similarly to the M5CoreS3 lib.

**Comment by egnor** [comment]
@Tinyu-Zhao to clarify:
- the M5Core2 library is deprecated (probably you won't DELETE it, but you'll stop updating it soon if not already)
- the [M5Unified library](https://github.com/m5stack/M5Unified) is the recommended basis for new code
- BUT the M5Unified library will be migrated into this repository (m5stack/M5Core2) in the future so watch out for that
did I get it right?

Please change the deprecation warning to "Please switch to the M5Unified library"? (The talk of "will be discontinued soon" is confusing.)

**Comment by Tinyu-Zhao** [comment]
> @Tinyu-Zhao to clarify:
> 
> * the M5Core2 library is deprecated (probably you won't DELETE it, but you'll stop updating it soon if not already)
> * the [M5Unified library](https://github.com/m5stack/M5Unified) is the recommended basis for new code
> * BUT the M5Unified library will be migrated into this repository (m5stack/M5Core2) in the future so watch out for that
> 
> Did I get it right?
> 
> If so, please change the deprecation warning to "Please switch to the M5Unified library"? (The talk of "will be discontinued soon" is confusing.)

yes, I will change

**Comment by KevinJansenn** [comment]
They did not change the warning
