### ISSUE TITLE
The pin definition of Wire.begin in M5Core2.cpp is in conflict

### ISSUE THREAD

**Issue by tomorrow56** [m5stack/M5Core2#2]
I think the wire.begin pin definition should have been PA_SDA/PA_SCL because of Unit's sketch compatibility, but it has the same pins as Wire1 that are in conflict.
I think the following pins are correct.
`
void M5Core2::begin(bool LCDEnable, bool SDEnable, bool SerialEnable, bool I2CEnable) {
 .....

// I2C init
  if (I2CEnable == true) {
//    Wire.begin(21, 22);
    Wire.begin(32, 33);
  }
`

**Comment by Tinyu-Zhao** [comment]
Thank you for your help, we have [fixed the problem](https://github.com/m5stack/M5Core2/commit/494dc9be4704331da06ad934ed2b52e9f3945b8b).
