### ISSUE TITLE
RTC & Sleep Examples need to be renamed

### ISSUE THREAD

**Issue by revta** [m5stack/M5Core2#21]
Issue with latest examples. Arduino IDE needs file and folder name to match in order to show up in the examples. The two issues specifically:

examples/RTC 
examples/sleep

the .ino files should be renamed to match the folder names.

At least this is the issue with getting them to register in Arduino 1.8.13 on MacOS 10.14.6

**Comment by felmue** [comment]
Hello @revta 

you are absolutely correct. [Pull-request](https://github.com/m5stack/M5Core2/pull/22) created.

Thanks
Felix
