### ISSUE TITLE
Release 0.0.2 is not available in Arduino Library Manager

### ISSUE THREAD

**Issue by digi-thomas2003** [m5stack/M5Core2#23]
Hello together,

since a fes days release 0.0.2 is available here in Github.
But unfortunately it is not available in the Arduino Library Manager.

Can you please add this new release there?
Thank you!!

Thomas

**Comment by mlukasek** [comment]
Even if you download it manually, the library.json has 0.0.1 inside.

**Comment by Gitshaoxiang** [comment]
yeah.....has some mistake...I will release it again.. thank you feedback

**Comment by Gitshaoxiang** [comment]
fixed
