### ISSUE TITLE
I get a compilation error in version 0.0.2.

### ISSUE THREAD

**Issue by FumikiNakao** [m5stack/M5Core2#24]
If you use the following function to use the RTC (real-time clock) function, a compile error will occur.

M5.Rtc.GetData ()
M5.Rtc.SetData ()

After reverting the version to 0.0.1, the error no longer occurs.

**Comment by tobozo** [comment]
`SetData` => `SetDate`

`GetData` => `GetDate`

**Comment by FumikiNakao** [comment]
> `SetData` => `SetDate`
> 
> `GetData` => `GetDate`

Thanks.
