### ISSUE TITLE
sprite.setPsram is not implemented

### ISSUE THREAD

**Issue by tobozo** [m5stack/M5Core2#30]
there is a sprite::setPsram in sprite.h, but the implementation has been removed from the .cpp file, why ???

this is a pity since it's only a setter for a bool, and is very practical to unlock fullscreen sprites in 8 bits color mode

```C
void TFT_eSprite::setPsram( bool enable )
{
  _usePsram = enable;
}
```

**Comment by Tinyu-Zhao** [comment]
Hi, I checked the edit log for Sprite.cpp and it seems that setPsram was not there to begin with, you can create a PR if you like, we would be happy to accept it.
