### ISSUE TITLE
ECG example not working in Core2

### ISSUE THREAD

**Issue by iPsych** [m5stack/M5Core2#31]
It seems ECG example is not working in Core2.
Adjusted Serial lines doesn't work like described.
Is there more modification needed?

**Comment by felmue** [comment]
Hello @iPsych 

I don't have the ECG module, but I think the GPIOs should be changed from 13, 5 to 19, 33.
Eg. try to modify this line:
`Serial1.begin(115200,SERIAL_8N1,13,5);`
to
`Serial1.begin(115200,SERIAL_8N1,19,33);`

As a reference - [the differences of the M5Stack bus and M5Core2 bus](https://www.gwendesign.ch/kb/m5stack/m5core2/#m5core2-bus-and-gpios-compared-to-m5stack).

Good luck!
Felix

**Comment by iPsych** [comment]
@felmue 
Thanks.
It was the problem! The correct pin allows to run the example in Core2.
