### ISSUE TITLE
AXP192 code error

### ISSUE THREAD

**Issue by Kabron287** [m5stack/M5Core2#40]
In function
```
uint32_t AXP192::Read32bit(uint8_t Addr)   

 Wire1.requestFrom(0x34, 2);
```
should looks like
```
 Wire1.requestFrom(0x34, 4);
```
this solves error counting Coulomb Measures

**Comment by Tinyu-Zhao** [comment]
Thank for you help, we have now [fixed](https://github.com/m5stack/M5Core2/blob/0b905c583003eaccdf81c2f82b235f186903ca69/src/AXP192.cpp#L152) this issue.
