### ISSUE TITLE
vector class is undefined and an error occurs

### ISSUE THREAD

**Issue by nagasawa** [m5stack/M5Core2#42]
M5Display.h

append
`#include <vector>`

**Comment by take4mats** [comment]
This fixes below error I saw while executing trivial hello world sketch.  This is too easy fix, so am I missing something???

```cpp
#include <M5Core2.h>

void setup() {
  M5.begin();
  M5.Lcd.setTextSize(3);
  M5.Lcd.print("Hello World");
}

void loop() {
}
```

error log:

```
~/Documents/Arduino/libraries/M5Core2/src/M5Display.h:117:12: error: 'vector' in namespace 'std' does not name a template type
       std::vector<DisplayState> _displayStateStack;
```

**Comment by bhupiister** [comment]
I had the same problem, but in my case the issue was installation of wrong library. I was using M5 core2 but had installed library for M5 stack on Arduino IDE

**Comment by Tinyu-Zhao** [comment]
Thanks, fixed
