### ISSUE TITLE
Add Russian language to Font

### ISSUE THREAD

**Issue by SlimRG** [m5stack/M5Core2#50]
Add Russian lang to fonts.
This chars:
Аа Бб Вв Гг Дд Ее Ёё Жж Зз Ии Йй Кк Лл Мм Нн Оо Пп Рр Сс Тт Уу Фф Хх Цц Чч Шш Щщ Ъъ Ыы Ьь Ээ Юю Яя

**Comment by Tinyu-Zhao** [comment]
You can try to use the lib of [GFX](https://github.com/m5stack/M5GFX)
