### ISSUE TITLE
In Core2 there no M5.Power functions

### ISSUE THREAD

**Issue by SlimRG** [m5stack/M5Core2#57]
In Core2 there no M5.Power functions.
I know that here is AXP192 chip.
But there no getBatteryLevel() function

**Comment by Tinyu-Zhao** [comment]
You can use the function GetBatVoltage() to read his voltage, the standard voltage is 3.7V.

**Comment by SlimRG** [comment]
#58 https://github.com/m5stack/M5Core2/pull/58
