### ISSUE TITLE
GPS unit example uses incorrect GPIOs for RX and TX

### ISSUE THREAD

**Issue by felmue** [m5stack/M5Core2#75]
Hello M5Stack engineers

the GPS unit [example](https://github.com/m5stack/M5Core2/blob/master/examples/Unit/GPS_AT6558/FullExample/FullExample.ino) for M5Core2 seems to only have been copied verbatim from the M5Stack example except for the include file. Sorry, that is not enough, as M5Stack uses GPIOs 16 and 17 for RX and TX whereas M5Core2 uses GPIOs 13 and 14.

This line `ss.begin(GPSBaud);` in the example needs to be replaced with `ss.begin(GPSBaud, SERIAL_8N1, 13, 14);`.

Please also see this [thread](https://community.m5stack.com/topic/3759/invalid-values-on-gps-unit) from the community forum.

Thanks
Felix

P.S. I know I could provide a pull-request, but from my experience in the past, PRs are mostly ignored anyways, so I won't bother doing that.

**Comment by Tinyu-Zhao** [comment]
Thank you for your help, we have corrected this error
