### ISSUE TITLE
M-BUS hardware no GPIO 5 SPI CS exposed 

### ISSUE THREAD

**Issue by wurst44** [m5stack/M5Core2#76]
This is more like a hardware question, in Core Basic the SPI CS (GPIO 5) was exposed in M-BUS. Has this been removed in Core2?
Is it not essential for using SPI over the bus?
So all add-ons for core basic are incompatible with core2? 

![Screenshot_20211208_225405](https://user-images.githubusercontent.com/2656697/145290638-c95a3cd3-65b2-43ec-94be-f3e19daf3eec.jpg)
![Screenshot_20211208_225321](https://user-images.githubusercontent.com/2656697/145290658-bdc473ce-d90c-48bd-a34e-39d7ac14790b.jpg)

**Comment by felmue** [comment]
Hello @wurst44 

the good thing about ESP32 is that almost every function can be configured to use almost any GPIOs. For many functions, like SPI, there are some GPIOs defined as default, but any of the GPIOs used for SPI can be changed as needed.

The LAN module for instance uses GPIO26 as SPI CS (which btw is the same for M5Stack (Base, Gray, Fire) and M5Core2. Have a look [here](https://github.com/m5stack/M5-ProductExampleCodes/blob/master/Base/LAN/Arduino/W5500/WebServer/WebServer.ino).

Thanks
Felix
