### ISSUE TITLE
Typos in the comment of examples/Basics/sleep/sleep.ino

### ISSUE THREAD

**Issue by cyclexit** [m5stack/M5Core2#88]
https://github.com/m5stack/M5Core2/blob/d11e848f3704434fa0d216ba05fd130502528bbc/examples/Basics/sleep/sleep.ino#L40

The comment should change the "light sleep" to "deep sleep". 然后把“轻度睡眠”改成“深度睡眠”
```cpp
M5.Axp.DeepSleep(SLEEP_SEC(5)); //Wake up after 5 seconds of deep sleep, the CPU will reboot and the program will start from the beginning.  深度睡眠5秒后唤醒,CPU将重新启动，程序将从头开始执行
```

**Comment by Tinyu-Zhao** [comment]
Thank you for your reminder, I will fix it in time
