### ISSUE TITLE
Touch get wrong values more you go away from display center

### ISSUE THREAD

**Issue by gmgunderground** [m5stack/M5Core2#93]
M5.Touch get wrong X and Y values more you go away from display center. The same problem there is with M5Unified.
How to fix it? With this type of issue the display touch is compliteli  useless. X and Y are not centered with the touch point.

https://user-images.githubusercontent.com/3244031/173841031-1d5f2e2c-38b6-4404-a889-bf29629e8fa6.mp4

**Comment by Tinyu-Zhao** [comment]
You can try to use [M5Tool](https://github.com/m5stack/M5Tools) to upgrade the screen firmware to solve this problem
